/**
 * Builds public/styles.css: the global stylesheet, then every co-located
 * component stylesheet, then Tailwind's utilities.
 *
 * Component CSS lives next to its component (Component.tsx / Component.css) per
 * the project convention in docs/architecture.md. The dashboard is the exception it is
 * written in Tailwind utilities, generated from src/tailwind.css and appended
 * last so those utilities win on equal specificity.
 *
 * The browser still gets one small static file.
 */
import { execFile } from 'node:child_process';
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

const run = promisify(execFile);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const globalCss = join(root, 'src', 'App.css');
const componentsDir = join(root, 'src', 'components');
const out = join(root, 'public', 'styles.css');

const parts = [
  '/* Generated by scripts/build-css.mjs — edit src/App.css or src/components/*.css. */',
  `/* ---- App.css ---- */`,
  await readFile(globalCss, 'utf8'),
];

// Components are grouped by navigation area: common/, agent/, admin/.
async function collect(dir, prefix = '') {
  const entries = await readdir(dir, { withFileTypes: true });
  const found = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.isDirectory()) found.push(...(await collect(join(dir, entry.name), `${prefix}${entry.name}/`)));
    else if (entry.name.endsWith('.css')) found.push({ path: join(dir, entry.name), label: prefix + entry.name });
  }
  return found;
}

const files = await collect(componentsDir);
for (const file of files) {
  parts.push(`/* ---- components/${file.label} ---- */`);
  parts.push(await readFile(file.path, 'utf8'));
}

// Tailwind scans the dashboard sources itself (see the @source lines in
// src/tailwind.css) and prints the generated CSS to stdout.
const tailwindIn = join(root, 'src', 'tailwind.css');
const { stdout: tailwind } = await run(
  'npx',
  ['@tailwindcss/cli', '--input', tailwindIn, '--cwd', root],
  { cwd: root, maxBuffer: 32 * 1024 * 1024 },
);

parts.push('/* ---- tailwind (dashboard utilities) ---- */');
parts.push(tailwind);

await mkdir(dirname(out), { recursive: true });
await writeFile(out, parts.join('\n\n').trimEnd() + '\n');
console.log(
  `styles.css ← App.css + ${files.length} component stylesheets + tailwind (${(tailwind.length / 1024).toFixed(1)} kB)`,
);
