/**
 * Concatenates the global stylesheet and every co-located component stylesheet
 * into public/styles.css.
 *
 * Component CSS lives next to its component (Component.tsx / Component.css) per
 * the project convention in CLAUDE.md. Nothing else here is a build step: no
 * bundler, no dependencies, no transform — just a deterministic concat so the
 * browser still gets one small static file.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const globalCss = join(root, 'src', 'App.css');
const componentsDir = join(root, 'src', 'components');
const out = join(root, 'public', 'styles.css');

const parts = [
  '/* Generated by scripts/build-css.mjs — edit src/App.css or src/components/*.css. */',
  `/* ---- App.css ---- */`,
  await readFile(globalCss, 'utf8'),
];

// Components are grouped by navigation area: common/, agent/, admin/.
async function collect(dir, prefix = '') {
  const entries = await readdir(dir, { withFileTypes: true });
  const found = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.isDirectory()) found.push(...(await collect(join(dir, entry.name), `${prefix}${entry.name}/`)));
    else if (entry.name.endsWith('.css')) found.push({ path: join(dir, entry.name), label: prefix + entry.name });
  }
  return found;
}

const files = await collect(componentsDir);
for (const file of files) {
  parts.push(`/* ---- components/${file.label} ---- */`);
  parts.push(await readFile(file.path, 'utf8'));
}

await mkdir(dirname(out), { recursive: true });
await writeFile(out, parts.join('\n\n').trimEnd() + '\n');
console.log(`styles.css ← App.css + ${files.length} component stylesheets`);
