#!/usr/bin/env bash
#
# One command to get this app running: secrets, dependencies, stylesheet,
# database, seed data.
#
#   ./scripts/setup.sh              # on this machine, using the local toolchain
#   ./scripts/setup.sh --docker     # in a container, no Node needed on the host
#   ./scripts/setup.sh --fresh      # throw the local database away and rebuild
#   ./scripts/setup.sh --docker --fresh --start
#
# A note on "the database": D1 is Cloudflare's SQLite, and there is no server to
# point Docker at. `wrangler dev` runs it locally as a file under .wrangler/state
# — so the Docker path containerises the *worker*, and its D1 file lives in the
# bind-mounted project directory. Both paths therefore share one database, and
# you can switch between them freely.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

MODE=local
FRESH=0
START=0

for arg in "$@"; do
  case "$arg" in
    --docker) MODE=docker ;;
    --local) MODE=local ;;
    --fresh) FRESH=1 ;;
    --start) START=1 ;;
    -h | --help)
      # The header comment above, up to the first line of actual script.
      awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)" >&2
      exit 2
      ;;
  esac
done

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
step() { printf '\n\033[1;32m▸\033[0m \033[1m%s\033[0m\n' "$1"; }
note() { printf '  %s\n' "$1"; }

# ---------------------------------------------------------------- 1. secrets

# ADMIN_PASSCODE is the one-time setup key for creating the first admin
# account; SESSION_SECRET signs both cookies. Generated, never committed —
# .dev.vars is git-ignored.
random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    node -e "console.log(require('node:crypto').randomBytes(24).toString('hex'))"
  fi
}

step "Local secrets (.dev.vars)"
if [ -f .dev.vars ]; then
  note ".dev.vars already exists — left untouched."
else
  cat > .dev.vars <<EOF
# Generated by scripts/setup.sh. Git-ignored. Never commit this file.
# ADMIN_PASSCODE is the one-time setup key for /admin/setup, not a password.
ADMIN_PASSCODE="$(random_secret)"
SESSION_SECRET="$(random_secret)"
EOF
  chmod 600 .dev.vars
  note "Wrote .dev.vars with fresh random values."
fi

# --------------------------------------------------------------- 2. database

if [ "$FRESH" = "1" ] && [ -d .wrangler/state ]; then
  step "Removing the local database (--fresh)"
  rm -rf .wrangler/state
  note "Deleted .wrangler/state — migrations and seed will rebuild it."
fi

# ------------------------------------------------- what to do next, printed
# at the end of either path (and before `--start` hands over to a long-running
# process, which never returns).

summary() {
  cat <<'EOF'

  Sign in
  ───────
  Sales agent   http://localhost:8787/          — name and phone, no password
  Admin         http://localhost:8787/admin     — admin@pluck.ng / pluck-demo-admin

  Nothing in the sales-agent app links to /admin. That is deliberate: an agent
  never needs it. The line above and README.md are the only places it is
  written down.

  That admin account comes from seed.sql and is a KNOWN credential — anyone
  with this repo has it. Before real sales agents use this deployment, add a
  named account in Settings → Team and delete the demo one:

    npx wrangler d1 execute pluck-training --local \
      --command "DELETE FROM admins WHERE email = 'admin@pluck.ng'"

  With no admins left, /admin/login redirects to /admin/setup, which creates the
  first real account using the ADMIN_PASSCODE in .dev.vars as its setup key.

  No training material is published yet: paste the Google Drive links into
  Admin → Settings. For a demo without Drive, point it at the bundled
  stand-in pages instead, which also shortens the gate to 10 seconds:

    npm run db:mock:local

EOF
}

# ------------------------------------------------------- 3a. the Docker path

if [ "$MODE" = "docker" ]; then
  if ! docker compose version >/dev/null 2>&1; then
    echo "Docker Compose v2 is required for --docker (try: docker compose version)." >&2
    exit 1
  fi

  step "Building the image"
  docker compose build

  # No npm install here: the image already ran `npm ci`, and a `compose run`
  # container gets its own node_modules volume seeded from that image.
  step "Building public/styles.css"
  docker compose run --rm --no-deps app npm run build:css

  step "Applying migrations and seeding"
  docker compose run --rm --no-deps app npm run db:migrate:local
  docker compose run --rm --no-deps app npm run db:seed:local

  step "Ready"
  note "Start it with:  docker compose up      → http://localhost:8787"
  note "Port taken?     PORT=8788 docker compose up"
  note "Stop it with:   docker compose down"
  if [ "$START" = "1" ]; then
    summary
    exec docker compose up
  fi

# -------------------------------------------------------- 3b. the local path

else
  command -v node >/dev/null 2>&1 || {
    echo "Node is required (or run with --docker)." >&2
    exit 1
  }

  step "Installing dependencies"
  if [ -d node_modules ] && [ "$FRESH" != "1" ]; then
    note "node_modules is present — skipping (use --fresh to reinstall)."
  else
    npm install
  fi

  step "Building public/styles.css"
  npm run build:css

  step "Applying migrations and seeding"
  npm run db:migrate:local
  npm run db:seed:local

  step "Ready"
  note "Start it with:  npm run dev           → http://localhost:8787"
  if [ "$START" = "1" ]; then
    summary
    exec npm run dev
  fi
fi

summary
